name: stack_controls
description: Flame example game on how to use Stack widgets to create floating controls

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^0.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
