name: flare_rotation
description: Flare example with rotation

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flame:
    path: ../../flame

flutter:
  assets:
    - assets/Bob_Minion.flr
